travis:
  secure:
    BINSTAR_TOKEN: jiT00LZ59rBz0cfMDniNgq76ichQ6ufVHPA26gTzRG1+WHEGZDLnOdM0e4lZ+AK+GbtTjuskhVn1OeTBDdmLXsMxXHOY0/ZJDGcq6L7cAMRYtQXnrSDoUh1PiMdO1lSI6podSYikwma+xVptbQ+JR7QbQllsdgtNU18rpUKvaHxqRkrgXrzy20xV9yFR9sLvjKp9nIFBFLokRWb8b4lxHZqNqxtgLAIrBxve9gE/H1k++BYQOmdcRo0LiS0e6fiXBYrRDk9ou1vkOVRKa9dpv0scQkhQAGv3YGriroEY+CA0PP0B+geRFxeA43EcunbEbFx2HGpB/YmiQ2ByQxpoPPgUgKFHyEAS/+LOMnwEdRijEct3c88+AuQgdYr1fY9hT1eX2dOPOIS+5BLcuhN2/Kr+jznXkIvOdpfL5eO5zBnqc0h5S2tG2dAug6gQqkCMS3QFhmqMANDna9HAFmmc6kith+YdrmGIA/nIvpfnQMv5RBNuuDfcQJYqGdtHILDbAHV/kwWUs5T9wWZiD+Wjd3oUxjoGC6WfmU/bYyNQ98h0F3djZFq6pDR1loMGl2Jj4A6wxmv207J+Yj+6iRJzFOb1pNdstsGHqZmGjWVFLKGcvIv6ibbAWzV9+L2zh03vBk1XqYS9c5/F5FVMQCwGkfn4SUjjfSu1ZaM6dR5avx4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
